changes for automation

diff --git a/.github/workflows/publish-on-tag.yml b/.github/workflows/publish-on-tag.yml
--- a/.github/workflows/publish-on-tag.yml
+++ b/.github/workflows/publish-on-tag.yml
@@ -30,6 +30,7 @@ jobs:
       - name: Authenticate with npm
         run: |
             echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
+            npm whoami || echo "Authentication failed"
 
 
       # Step 3: Install dependencies
